export const TEXT_VALIDATION = {
  MEANINGFUL_PATTERNS: [
    /\b(что|как|почему|когда|где|кто|какой|зачем|объясни|расскажи|опиши|в чем)\b/i,
    /\b(what|how|why|when|where|who|which|explain|describe|tell me|difference)\b/i,
    /\b(программир|код|функц|перемен|база|данн|сервер|клиент|алгоритм|интерфейс)\b/i,
    /\b(program|code|function|variable|data|server|client|algorithm|interface)\b/i,
    /\b(это|так|есть|быть|мочь|хотеть|знать|объяснить|рассказать)\b/i,
    /\b(is|are|have|can|will|know|explain|describe|tell)\b/i,
    /\b(отличие|разница|разницу|различия|отличия|что такое|как работает|зачем нужен|для чего используется)\b/i,
    /\b(чем отличается|в чем разница|какая разница|как использовать|как создать|как написать)\b/i,
    /\b(difference|between|what is|how does|why use|when to use|purpose of)\b/i,
    /\b(how to use|what are the differences|what is the difference|how to create|how to write)\b/i,
    /\b(структур|организац|проект|компонент|модул|архитектур|паттерн|шаблон)\b/i,
    /\b(structure|organize|project|component|module|architecture|pattern)\b/i,
    /\b(как вы|как ты|как лучше|как правильно|как оптимальн|как эффективн)\b/i,
    /\b(how do you|how to|best way|proper way|optimal way|efficient way)\b/i,
  ] as const,

  GIBBERISH_PATTERNS: [
    /^[0-9\s]{3,}$/,
    /^(.)\1{4,}$/,
    /^[^\w\s\p{L}]{3,}$/u,
    /^(йцукенгшщзхъ|фывапролджэ|ячсмитьбю|qwertyuiop|asdfghjkl|zxcvbnm)$/i,
    /(.)\1{5,}/,
    /^(?=.*[\u0430-\u044F\u0451])(?=.*[a-z])[\u0430-\u044F\u0451a-z\s]+$/i,
    /^(?=.*[a-z])(?=.*[\u0430-\u044F\u0451])[a-z\u0430-\u044F\u0451\s]+$/i,
  ] as const,

  MEANINGFUL_SHORT_WORDS: [
    'ооп',
    'api',
    'sql',
    'css',
    'html',
    'js',
    'ts',
    'vue',
    'react',
    'dom',
    'url',
    'ide',
    'sdk',
    'cdn',
    'ssl',
    'tls',
    'http',
    'json',
    'xml',
    'git',
    'что',
    'как',
    'чем',
    'кто',
    'где',
    'когда',
    'почему',
    'зачем',
    'this',
    'that',
    'what',
    'how',
    'why',
    'when',
    'where',
    'var',
    'let',
    'const',
    'function',
    'class',
    'interface',
    'type',
    'if',
    'else',
    'for',
    'while',
    'return',
    'import',
    'export',
    'отличие',
    'разница',
    'отличия',
    'различия',
  ] as const,

  IT_TERMS: [
    'javascript',
    'typescript',
    'python',
    'java',
    'csharp',
    'cplusplus',
    'php',
    'ruby',
    'go',
    'rust',
    'js',
    'ts',
    'py',
    'cs',
    'cpp',
    'rb',
    'rs',
    'react',
    'vue',
    'angular',
    'svelte',
    'next',
    'nuxt',
    'express',
    'django',
    'flask',
    'laravel',
    'spring',
    'aspnet',
    'jquery',
    'bootstrap',
    'tailwind',
    'ооп',
    'oop',
    'api',
    'rest',
    'graphql',
    'sql',
    'nosql',
    'mongodb',
    'postgresql',
    'mysql',
    'html',
    'css',
    'scss',
    'sass',
    'dom',
    'virtual dom',
    'ajax',
    'fetch',
    'websocket',
    'docker',
    'kubernetes',
    'ci/cd',
    'devops',
    'agile',
    'scrum',
    'kanban',
    'git',
    'github',
    'gitlab',
    'bitbucket',
    'npm',
    'yarn',
    'webpack',
    'vite',
    'solid',
    'dry',
    'kiss',
    'yagni',
    'mvc',
    'mvvm',
    'microservices',
    'monolith',
    'singleton',
    'factory',
    'observer',
    'decorator',
    'adapter',
    'strategy',
    'отличие',
    'разница',
    'отличия',
    'различия',
    'область видимости',
    'scope',
    'hoisting',
    'всплытие',
    'closure',
    'замыкание',
    'promise',
    'async',
    'await',
    'callback',
    'event loop',
    'prototype',
    'прототип',
    'inheritance',
    'наследование',
    'encapsulation',
    'инкапсуляция',
    'polymorphism',
    'полиморфизм',
    'структура',
    'организация',
    'проект',
    'компонент',
    'модуль',
    'архитектура',
    'паттерн',
    'шаблон',
    'структурировать',
    'организовать',
    'код',
    'code',
    'structure',
    'organize',
    'project',
    'component',
    'module',
    'architecture',
    'pattern',
    'большой проект',
    'large project',
    'codebase',
    'code base',
    'проектирование',
    'design',
  ] as const,

  TECHNICAL_QUESTION_PATTERNS: [
    /(?:^|\s)(?:что|как|почему|чем|зачем|когда|где)\s+(?:такое|работает|отличается|нужен|используется)/i,
    /(?:^|\s)(?:what|how|why|when|where)\s+(?:is|does|works|difference|purpose)/i,
    /(?:^|\s)отличие\s+(?:между|от)/i,
    /(?:^|\s)разница\s+(?:между|от)/i,
    /(?:^|\s)difference\s+(?:between|from)/i,
    /(?:^|\s)как\s+работает/i,
    /(?:^|\s)how\s+does\s+it\s+work/i,
    /(?:^|\s)что\s+такое/i,
    /(?:^|\s)what\s+is/i,
    /(?:^|\s)для\s+чего\s+нужен/i,
    /(?:^|\s)what\s+is\s+the\s+purpose/i,
    /(?:^|\s)зачем\s+нужен/i,
    /(?:^|\s)why\s+use/i,
  ] as const,

  // Слова, которые почти всегда указывают на нормальный вопрос
  MEANINGFUL_QUESTION_WORDS: [
    'отличие',
    'разница',
    'отличия',
    'различия',
    'что такое',
    'как работает',
    'зачем нужен',
    'для чего',
    'чем отличается',
    'в чем разница',
    'какая разница',
    'что значит',
    'как использовать',
    'как создать',
    'как написать',
    'what is',
    'how does',
    'why use',
    'when to use',
    'purpose of',
    'difference between',
    'как вы',
    'как ты',
    'как лучше',
    'как правильно',
    'как оптимально',
    'как эффективно',
    'how do you',
    'how to',
    'best way',
    'proper way',
  ] as const,
} as const
