import type { AISettings, Question } from '@/types/interview'
import { huggingFaceService, RECOMMENDED_MODELS } from './huggingFaceService'

const isHuggingFaceConfigured = !!import.meta.env.VITE_HUGGING_FACE_API_KEY

console.log('Hugging Face configured:', isHuggingFaceConfigured)

export const AIService = {
  /**
   * Генерация вопросов через Hugging Face
   */
  async generateQuestions(settings: AISettings): Promise<Question[]> {
    console.log('Generating questions with settings:', settings)

    try {
      let questions: string[] = []

      if (isHuggingFaceConfigured) {
        console.log('Using Hugging Face Inference API')
        questions = await huggingFaceService.generateQuestions(settings)

        if (questions.length === 0) {
          throw new Error('No questions generated by API')
        }

        console.log(`Generated ${questions.length} questions via Hugging Face`)
      }
      else {
        console.log('Using local questions fallback')
        questions = await this.generateLocalQuestions(settings)
      }

      return questions.map((text, index) => ({
        id: `ai-${Date.now()}-${index}`,
        text: text.trim(),
        type: 'text' as const,
        category: settings.field,
        difficulty: settings.difficulty,
        tags: settings.technology ? [settings.technology] : [settings.field],
        generatedBy: 'ai' as const,
        createdAt: new Date(),
        source: isHuggingFaceConfigured ? 'hugging-face' : 'local',
      }))
    }
    catch (error) {
      console.error('AI Service Error:', error)

      // Fallback на локальные вопросы
      console.log('Falling back to local questions')
      const localQuestions = await this.generateLocalQuestions(settings)

      return localQuestions.map((text, index) => ({
        id: `ai-fallback-${Date.now()}-${index}`,
        text,
        type: 'text' as const,
        category: settings.field,
        difficulty: settings.difficulty,
        tags: settings.technology ? [settings.technology] : [settings.field],
        generatedBy: 'ai' as const,
        createdAt: new Date(),
        source: 'local-fallback',
      }))
    }
  },

  /**
   * Локальные вопросы для fallback
   */
  async generateLocalQuestions(settings: AISettings): Promise<string[]> {
    await new Promise(resolve => setTimeout(resolve, 1000))

    const questionsByField = {
      frontend: {
        junior: [
          'Что такое HTML и для чего он используется?',
          'Объясните разницу между блочными и строчными элементами',
          'Что такое CSS и как он используется для стилизации?',
        ],
        middle: [
          'Объясните принципы реактивности во Vue 3',
          'В чем разница между Composition API и Options API?',
          'Как работает виртуальный DOM?',
        ],
        senior: [
          'Опишите архитектуру крупного Vue-приложения',
          'Как оптимизировать производительность Vue-приложения?',
          'Расскажите о механизмах кэширования в веб-приложениях',
        ],
      },
      backend: {
        junior: [
          'Что такое REST API?',
          'Объясните основные HTTP методы',
          'Что такое база данных и зачем она нужна?',
        ],
        middle: [
          'В чем разница между SQL и NoSQL базами данных?',
          'Что такое индексы в базах данных?',
          'Объясните принципы ООП',
        ],
        senior: [
          'Опишите подходы к проектированию микросервисной архитектуры',
          'Как обеспечить безопасность API?',
          'Что такое message brokers и зачем они нужны?',
        ],
      },
    }

    const fieldQuestions = questionsByField[settings.field] || questionsByField.frontend
    const difficultyQuestions = fieldQuestions[settings.difficulty] || fieldQuestions.junior

    return difficultyQuestions.slice(0, settings.questionsCount)
  },

  /**
   * Оценка ответа через AI
   */
  async evaluateAnswer(question: string, answer: string): Promise<{
    score: number
    feedback: string
    suggestions: string[]
  }> {
    if (!answer.trim()) {
      return {
        score: 0,
        feedback: 'Ответ отсутствует',
        suggestions: ['Попробуйте сформулировать ответ на вопрос'],
      }
    }

    if (isHuggingFaceConfigured) {
      try {
        return await huggingFaceService.evaluateAnswer(question, answer)
      }
      catch (error) {
        console.error('AI evaluation error, using fallback:', error)
      }
    }

    // Fallback оценка
    return {
      score: Math.floor(Math.random() * 3) + 7,
      feedback: 'Для точной оценки подключите Hugging Face API',
      suggestions: [
        'Уточните технические детали',
        'Добавьте примеры из опыта',
        'Структурируйте ответ четче',
      ],
    }
  },

  /**
   * Проверка доступности AI API
   */
  isAIAvailable(): boolean {
    return isHuggingFaceConfigured
  },

  /**
   * Тестирование подключения
   */
  async testConnection(): Promise<boolean> {
    if (!isHuggingFaceConfigured) {
      return false
    }

    try {
      return await huggingFaceService.testConnection()
    }
    catch (error) {
      console.error('Connection test failed:', error)
      return false
    }
  },

  /**
   * Получение информации о модели
   */
  getModelInfo(): string {
    return isHuggingFaceConfigured
      ? `Hugging Face Inference API (${RECOMMENDED_MODELS.GENERAL})`
      : 'Локальный режим (без AI)'
  },
}
