import type { AIAnswer, AISettings, Question } from '@/types/interview'
import { huggingFaceService } from './huggingFaceService'

export const AIService = {
  /**
   * Генерация вопросов через защищенный API
   */
  async generateQuestions(settings: AISettings): Promise<Question[]> {
    try {
      const questions = await huggingFaceService.generateQuestions(settings)

      if (questions.length === 0) {
        throw new Error('No questions generated by API')
      }

      const tags = this.generateSmartTags(settings)

      return questions.map((text, index) => ({
        id: `ai-${Date.now()}-${index}`,
        text: text.trim(),
        type: 'text' as const,
        category: settings.specialty,
        difficulty: settings.difficulty,
        tags,
        generatedBy: 'ai' as const,
        createdAt: new Date(),
        source: 'hugging-face',
      }))
    }
    catch (error) {
      console.error('AI Service Error (fallback to local):', error)

      // Fallback: если бэкенд недоступен, выдаем локальные вопросы
      const localQuestions = await this.generateLocalQuestions(settings)
      const tags = this.generateSmartTags(settings)

      return localQuestions.map((text, index) => ({
        id: `ai-fallback-${Date.now()}-${index}`,
        text,
        type: 'text' as const,
        category: settings.specialty,
        difficulty: settings.difficulty,
        tags,
        generatedBy: 'ai' as const,
        createdAt: new Date(),
        source: 'local-fallback',
      }))
    }
  },

  /**
   * Умное формирование тегов без дублирования с категорией
   */
  generateSmartTags(settings: AISettings): string[] {
    if (settings.skill === 'soft') {
      return []
    }

    const tags: string[] = []

    if (settings.technology && settings.technology !== settings.specialty) {
      tags.push(settings.technology)
    }

    return tags
  },

  /**
   * Локальные вопросы для fallback
   */
  async generateLocalQuestions(settings: AISettings): Promise<string[]> {
    await new Promise(resolve => setTimeout(resolve, 1000))

    const questionsByField = {
      frontend: {
        junior: [
          'Что такое HTML и для чего он используется?',
          'Объясните разницу между блочными и строчными элементами',
          'Что такое CSS и как он используется для стилизации?',
        ],
        middle: [
          'Объясните принципы реактивности во Vue 3',
          'В чем разница между Composition API и Options API?',
          'Как работает виртуальный DOM?',
        ],
        senior: [
          'Опишите архитектуру крупного Vue-приложения',
          'Как оптимизировать производительность Vue-приложения?',
          'Расскажите о механизмах кэширования в веб-приложениях',
        ],
      },
      backend: {
        junior: [
          'Что такое REST API?',
          'Объясните основные HTTP методы',
          'Что такое база данных и зачем она нужна?',
        ],
        middle: [
          'В чем разница между SQL и NoSQL базами данных?',
          'Что такое индексы в базах данных?',
          'Объясните принципы ООП',
        ],
        senior: [
          'Опишите подходы к проектированию микросервисной архитектуры',
          'Как обеспечить безопасность API?',
          'Что такое message brokers и зачем они нужны?',
        ],
      },
    }

    const fieldQuestions = questionsByField[settings.specialty as keyof typeof questionsByField] || questionsByField.frontend
    const difficultyQuestions = fieldQuestions[settings.difficulty as keyof typeof fieldQuestions] || fieldQuestions.junior

    return difficultyQuestions.slice(0, settings.questionsCount)
  },

  /**
   * Оценка ответа через наш API
   */
  async evaluateAnswer(question: string, answer: string): Promise<{
    score: number
    feedback: string
    suggestions: string[]
  }> {
    if (!answer.trim()) {
      return {
        score: 0,
        feedback: 'Ответ отсутствует',
        suggestions: ['Попробуйте сформулировать ответ на вопрос'],
      }
    }

    try {
      return await huggingFaceService.evaluateAnswer(question, answer)
    }
    catch (error) {
      console.error('AI evaluation error, using fallback:', error)
      return {
        score: Math.floor(Math.random() * 3) + 7,
        feedback: 'Ошибка соединения с ИИ-сервером. Попробуйте позже.',
        suggestions: [
          'Уточните технические детали',
          'Добавьте примеры из опыта',
          'Структурируйте ответ четче',
        ],
      }
    }
  },

  /**
   * Тестирование подключения к нашему бэкенду
   */
  async testConnection(): Promise<boolean> {
    try {
      return await huggingFaceService.testConnection()
    }
    catch (error) {
      console.error('Connection test failed:', error)
      return false
    }
  },

  /**
   * Генерация ответа на вопрос
   */
  async generateAnswer(question: string, userAnswer?: string, questionCategory?: string): Promise<AIAnswer> {
    try {
      return await huggingFaceService.generateAnswer(question, userAnswer, questionCategory)
    }
    catch (error) {
      console.error('AI answer generation error:', error)
      return {
        content: 'Извините, произошла ошибка связи с сервером ИИ. Проверьте подключение.',
        type: 'serious',
      }
    }
  },
}
